// Code generated by protoc-gen-go-masker. DO NOT EDIT.
// version: {{ .PluginVersion }}
// param UtilPkg: {{ .UtilPkg }}
// source: {{ .File.Proto.GetName }}

package {{ .File.GoPackageName }}

{{ range $m := .Messages }}
	func (x *{{ $m.GoIdent.GoName }}) Mask() any {
		if x == nil {
			return x
		}

		x1 := {{ $m.CloneFunc }}(x).(*{{ $m.GoIdent.GoName }})
		x1.mask()
		return x1
	}

	func (x *{{ $m.GoIdent.GoName }}) mask() {
		{{- if $m.HasMaskingFields }}
			{{- range $f := .Fields -}}
				{{- if $f.LeaveUnchanged -}}
					{{ continue }}
				{{- end -}}
				{{- if $f.IsRepeated }}
					for i := range x.{{ $f.GoName }} {
						{{ if $f.IsMasking -}}
							x.{{ $f.GoName }}[i] = {{ $f.MaskFunc }}(x.{{ $f.GoName }}[i])
						{{- else if $f.ImplementsMask -}}
							x.{{ $f.GoName }}[i].mask()
						{{- else if $f.ImplementsCloneMask -}}
							x.{{ $f.GoName }}[i] = x.{{ $f.GoName }}.Mask().(*{{ $.QualifiedGoIdent $f.Message.GoIdent }})
						{{- else -}}
							// x.{{ $f.GoName }}[i] = x.{{ $f.GoName }}[i]
						{{- end }}
					}
				{{ else if $f.IsOptional }}
					{{ if $f.IsMasking -}}
						{
							v := {{ $f.MaskFunc }}(*x.{{ $f.GoName }})
							x.{{ $f.GoName }} = &v
						}
					{{ else if $f.ImplementsMask -}}
						x.{{ $f.GoName }}.mask()
					{{ else if $f.ImplementsCloneMask -}}
						x.{{ $f.GoName }} = x.{{ $f.GoName }}.Mask().(*{{ $.QualifiedGoIdent $f.Message.GoIdent }})
					{{ else -}}
						// x.{{ $f.GoName }} = x.{{ $f.GoName }}
					{{ end -}}
				{{ else }}
					{{ if $f.IsMasking -}}
						x.{{ $f.GoName }} = {{ $f.MaskFunc }}(x.{{ $f.GoName }})
					{{ else if $f.ImplementsMask -}}
						x.{{ $f.GoName }}.mask()
					{{ else if $f.ImplementsCloneMask -}}
						x.{{ $f.GoName }} = x.{{ $f.GoName }}.Mask().(*{{ $.QualifiedGoIdent $f.Message.GoIdent }})
					{{ else -}}
						// x.{{ $f.GoName }} = x.{{ $f.GoName }}
					{{ end -}}
				{{ end }}
			{{- end -}}
		{{- end -}}
	}
{{ end }}
