// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: annotations.proto

package protomaskerpkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type As int32

const (
	As_Unspecified As = 0
	As_Generic     As = 1
	As_Password    As = 2
	As_Email       As = 3
	As_Phone       As = 4
	As_CardPAN     As = 5
)

// Enum value maps for As.
var (
	As_name = map[int32]string{
		0: "Unspecified",
		1: "Generic",
		2: "Password",
		3: "Email",
		4: "Phone",
		5: "CardPAN",
	}
	As_value = map[string]int32{
		"Unspecified": 0,
		"Generic":     1,
		"Password":    2,
		"Email":       3,
		"Phone":       4,
		"CardPAN":     5,
	}
)

func (x As) Enum() *As {
	p := new(As)
	*p = x
	return p
}

func (x As) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (As) Descriptor() protoreflect.EnumDescriptor {
	return file_annotations_proto_enumTypes[0].Descriptor()
}

func (As) Type() protoreflect.EnumType {
	return &file_annotations_proto_enumTypes[0]
}

func (x As) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use As.Descriptor instead.
func (As) EnumDescriptor() ([]byte, []int) {
	return file_annotations_proto_rawDescGZIP(), []int{0}
}

type MaskerOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	As            As                     `protobuf:"varint,1,opt,name=as,proto3,enum=As" json:"as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskerOptions) Reset() {
	*x = MaskerOptions{}
	mi := &file_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskerOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskerOptions) ProtoMessage() {}

func (x *MaskerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskerOptions.ProtoReflect.Descriptor instead.
func (*MaskerOptions) Descriptor() ([]byte, []int) {
	return file_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *MaskerOptions) GetAs() As {
	if x != nil {
		return x.As
	}
	return As_Unspecified
}

var file_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*MaskerOptions)(nil),
		Field:         47816,
		Name:          "masker",
		Tag:           "bytes,47816,opt,name=masker",
		Filename:      "annotations.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional MaskerOptions masker = 47816;
	E_Masker = &file_annotations_proto_extTypes[0]
)

var File_annotations_proto protoreflect.FileDescriptor

const file_annotations_proto_rawDesc = "" +
	"\n" +
	"\x11annotations.proto\x1a google/protobuf/descriptor.proto\"$\n" +
	"\rMaskerOptions\x12\x13\n" +
	"\x02as\x18\x01 \x01(\x0e2\x03.AsR\x02as*S\n" +
	"\x02As\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\v\n" +
	"\aGeneric\x10\x01\x12\f\n" +
	"\bPassword\x10\x02\x12\t\n" +
	"\x05Email\x10\x03\x12\t\n" +
	"\x05Phone\x10\x04\x12\v\n" +
	"\aCardPAN\x10\x05:G\n" +
	"\x06masker\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xf5\x02 \x01(\v2\x0e.MaskerOptionsR\x06maskerB2Z0github.com/bbars/proto-masker/pkg;protomaskerpkgb\x06proto3"

var (
	file_annotations_proto_rawDescOnce sync.Once
	file_annotations_proto_rawDescData []byte
)

func file_annotations_proto_rawDescGZIP() []byte {
	file_annotations_proto_rawDescOnce.Do(func() {
		file_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_annotations_proto_rawDesc), len(file_annotations_proto_rawDesc)))
	})
	return file_annotations_proto_rawDescData
}

var file_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_annotations_proto_goTypes = []any{
	(As)(0),                           // 0: As
	(*MaskerOptions)(nil),             // 1: MaskerOptions
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_annotations_proto_depIdxs = []int32{
	0, // 0: MaskerOptions.as:type_name -> As
	2, // 1: masker:extendee -> google.protobuf.FieldOptions
	1, // 2: masker:type_name -> MaskerOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_annotations_proto_init() }
func file_annotations_proto_init() {
	if File_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_annotations_proto_rawDesc), len(file_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_annotations_proto_goTypes,
		DependencyIndexes: file_annotations_proto_depIdxs,
		EnumInfos:         file_annotations_proto_enumTypes,
		MessageInfos:      file_annotations_proto_msgTypes,
		ExtensionInfos:    file_annotations_proto_extTypes,
	}.Build()
	File_annotations_proto = out.File
	file_annotations_proto_goTypes = nil
	file_annotations_proto_depIdxs = nil
}
